name: Wordstrong
favicon: null
layout_spectrum: 0.3600596524775028
typography_spectrum: 0.2064268325921148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#ffffff'
    - '#36b3a8'
    - '#7f8688'
    - '#424355'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.8169163651764393
  rhythmicContrast: 0.75
purpose: []
